config/routes.rb
Rails.application.routes.draw do
  get 'reports/show'

  get 'reports/index'

  require 'api_constraints'
  get 'products/show'

  root to: 'dashboard#index'
  # post 'api/recieve'
  # post 'api/recieve_order'
  get 'dashboard/index', as: 'dashboard'
  # post 'dashboard/show_with_timescale'
  # get 'dashboard/show_day', as: 'show_day'
  # get 'dashboard/show_week', as: 'show_week'
  # get 'dashboard/show_month', as: 'show_month'
  # get 'dashboard/show_custom_month'
  # post 'dashboard/show_custom_month'
  get 'orders/summary', as: "summary"
  get 'orders/show_monthly', as: "monthly_summary"
  resources :orders
  resources :products, only: [:show, :index]
  post 'sites/index', as: "custom_sites"
  get 'sites/index', as: "cutsom_sites"
  resources :sites
  devise_for :users
  resources :users


  namespace :api do
    scope module: :v1, costraints: ApiConstraints.new(version: 1, default: true) do
      post 'recieve', to: 'api#recieve'
      post 'recieve_order', to: 'api#recieve_order'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  belongs_to :site
  self.per_page = 35
  def self.show_monthly(time, user)
    Order.includes(:site).where(:created_at => time.beginning_of_month..time.end_of_month, user: user)
  end
  def self.total_monthly(time, user)
    Order.includes(:site).where(:created_at => time.beginning_of_month..time.end_of_month, user: user).sum(:total)
  end



end

app/controllers/orders_controller.rb
# TODO widok zamowien, przyjrzec sie optymalizacji dashboardu
# TODO orders = user.orders.where(created_at: Time.now.beginning_of_month.. Time.now).group_by(&:created_at)
# days.each do |day, order|

class OrdersController < ApplicationController
  before_action :set_order, only: [:destroy,:show, :update, :create, :edit]
  before_action :authenticate_user!
  def index
    @orders = current_user.orders.includes(:product).order(:created_at).paginate(:page => params[:page])
  end

  def show
  end

  def show_monthly
    time = Time.parse(params[:date])
    @orders = current_user.orders.where(created_at: time.beginning_of_day.. time.end_of_day)
  end

  def summary

    if params[:time]

      @time = Time.parse(params[:time])
    else
      @time = Time.zone.now
    end
    @orders = current_user.orders
                  .where(created_at: @time.beginning_of_month .. @time.end_of_month)
                  .group('created_at::date')
                  .sum(:total)
                  .sort_by { |order| order}
    # @orders = Order.show_monthly(time, current_user).paginate(:page => params[:page])

  end

  def edit
  end

  def create
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def new
  end
end

private

def set_order
  @order = Order.find(params[:id])
end

# def order_params
#   params.require(:order).permit(:name, :description)
# end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/views/orders/_form.html.haml
= simple_form_for @order do |f|
 -#= f.input :product_id
 -#= f.input :user_id
 = f.input :total
 = f.input :payment_type
 = f.input :name
 = f.input :surname
 = f.input :address
 = f.input :zip
 = f.input :city
 = f.input :description
 = f.input :phone_number
 = f.input :status
 = f.submit "zapisz", class: "btn btn-primary"

app/views/views/orders/_order.html.haml
%tr{id:"order_#{order.id}"}
  -#%td= order.id
  %td= order.ip
  %td= order.product.name
  %td= order.site.url
  %td= order.created_at.strftime("%d %b. %Y %H:%M")
  %td= order.total
  %td= order.payment_type
  %td= order.status
  -#%td= order.name
  -#%td= order.surname
  -#%td= order.phone_number
  -#%td= order.address
  -#%td= order.city
  -#%td= order.zip
  -#%td= order.status
  -#%td= order.description
  %td
    = link_to '', order_path(order), class: "btn btn-info btn-small glyphicon glyphicon-zoom-in", remote: true
    = link_to '', edit_order_path(order), class: "btn btn-info btn-small glyphicon glyphicon-pencil", remote: true
    = link_to '', order, method: :delete, class: "btn btn-danger btn-small glyphicon glyphicon-minus-sign", remote: true, data: {confirm: "Na pewno usunąć zamówienie?"}

app/views/views/orders/_order_list.haml
%p= @order.ip
%p= @order.product.name
%p= @order.site.url
%p= @order.created_at.strftime("%d %b. %Y %H:%M")
%p= "Zamówienie za: #{@order.total} zł"
%p= @order.payment_type
%p= @order.status
%p DANE ZAMAWIAJĄCEGO:
%p= @order.name
%p= @order.surname
%p= @order.phone_number
%p= @order.address
%p= @order.city
%p= @order.zip
%p= @order.status
%p= @order.description

app/views/views/orders/create.html.haml
%h1 Orders#create
%p Find me in app/views/orders/create.html.erb

app/views/views/orders/destroy.html.haml
%h1 Orders#destroy
%p Find me in app/views/orders/destroy.html.erb

app/views/views/orders/destroy.js.erb
$("#order_<%= @order.id %>").fadeOut();

app/views/views/orders/edit.html.haml
%h1 Orders#edit
%p Find me in app/views/orders/edit.html.erb
= render "form"

app/views/views/orders/edit.js.erb
$('#dialog h4').html("<i class=' glyphicon glyphicon-pencil'></i> Edytuj zamówienie");
$('.modal-body').html('<%= j render("form") %>');
$('#dialog').modal("show");
$('#dialog').on('shown.bs.modal', function () {
    $('.first_input').focus();
});

app/views/views/orders/index.html.haml
#orders
  %table.wrap.tablesorter
    %thead
      %tr
        -#%th{width: "3%"} #ID
        %th #IP
        %th #Produkt
        %th{width: "20%"} #Strona
        %th #utworzono
        %th{width: "5%"} #Kwota
        %th{width: "10%"} #Typ
        %th #status
        -#%th #Imię
        -#%th #Nazwisko
        -#%th #Telefon
        -#%th #Adres
        -#%th #Miasto
        -#%th #Kod
        -#%th #Stan
        -#%th #Uwagi
        %th #Akcje
    %tbody
      = render @orders
= will_paginate @orders, renderer: BootstrapPagination::Rails
  

app/views/views/orders/new.html.haml
%h1 Orders#new
%p Find me in app/views/orders/new.html.erb

app/views/views/orders/show.js.erb
$('#dialog h4').html("<i class=' glyphicon glyphicon-zoom-in'></i> Szczegóły zamówienia");
$('.modal-body').html('<%= j render("order_list", object: @order) %>');
$('#dialog').modal("show");
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/views/orders/show_monthly.html.haml
#orders
  %table.wrap.tablesorter
    %thead
      %tr
        -#%th{width: "3%"} #ID
        %th #IP
        %th #Produkt
        %th{width: "20%"} #Strona
        %th #utworzono
        %th{width: "5%"} #Kwota
        %th{width: "10%"} #Typ
        %th #status
        -#%th #Imię
        -#%th #Nazwisko
        -#%th #Telefon
        -#%th #Adres
        -#%th #Miasto
        -#%th #Kod
        -#%th #Stan
        -#%th #Uwagi
        - if current_user.admin?
          %th #Akcje
    %tbody
      -@orders.each do |order|
        %tr{id:"order_#{order.id}"}
          -#%td= order.id
          %td= order.ip
          %td= order.product.name
          %td= order.site.url
          %td= order.created_at.strftime("%d %b. %Y %H:%M")
          - if current_user.partner?
            %td= order.total * 0.3
          - else
            %td= order.total
          %td= order.payment_type
          %td= order.status
          -#%td= order.name
          -#%td= order.surname
          -#%td= order.phone_number
          -#%td= order.address
          -#%td= order.city
          -#%td= order.zip
          -#%td= order.status
          -#%td= order.description
          - if current_user.admin?
            %td
              = link_to '', order_path(order), class: "btn btn-info btn-small glyphicon glyphicon-zoom-in", remote: true
              = link_to '', edit_order_path(order), class: "btn btn-info btn-small glyphicon glyphicon-pencil", remote: true
              = link_to '', order, method: :delete, class: "btn btn-danger btn-small glyphicon glyphicon-minus-sign", remote: true, data: {confirm: "Na pewno usunąć zamówienie?"}

app/views/views/orders/summary.html.haml
#orders
  .current_month
    =link_to '', summary_path(time: @time - 1.month), class: 'glyphicon glyphicon-chevron-left'
    = @time.strftime("%Y %m")
    =link_to '', summary_path(time: @time + 1.month), class: 'glyphicon glyphicon-chevron-right'

  - @orders.each do |day,sum|
    .col-md-4
      %h2
        = day.strftime("%Y  %m %d")
        = link_to '', monthly_summary_path(date: day), class: "btn btn-info btn-small glyphicon glyphicon-zoom-in"
      - if current_user.partner?
        %p= "suma: #{sum * 0.3}"
      - else
        %p= "suma: #{sum}"