config/routes.rb
Rails.application.routes.draw do
  get 'reports/show'

  get 'reports/index'

  require 'api_constraints'
  get 'products/show'

  root to: 'dashboard#index'
  # post 'api/recieve'
  # post 'api/recieve_order'
  get 'dashboard/index', as: 'dashboard'
  # post 'dashboard/show_with_timescale'
  # get 'dashboard/show_day', as: 'show_day'
  # get 'dashboard/show_week', as: 'show_week'
  # get 'dashboard/show_month', as: 'show_month'
  # get 'dashboard/show_custom_month'
  # post 'dashboard/show_custom_month'
  get 'orders/summary', as: "summary"
  get 'orders/show_monthly', as: "monthly_summary"
  resources :orders
  resources :products, only: [:show, :index]
  post 'sites/index', as: "custom_sites"
  get 'sites/index', as: "cutsom_sites"
  resources :sites
  devise_for :users
  resources :users


  namespace :api do
    scope module: :v1, costraints: ApiConstraints.new(version: 1, default: true) do
      post 'recieve', to: 'api#recieve'
      post 'recieve_order', to: 'api#recieve_order'
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  # TODO lokalizacja czasu i maile
  def index

    #Visitor.where(created_at: (Time.now - 1.day)..(Time.now))

    @sites = current_user.sites.includes(:product, :orders, :visitors).where(visitors: {uniq: true}).order(visitors_count: :desc).limit(10)
    @t1 = Time.now - 7.day
    @t2 = Time.now
    @orders = Order.show_monthly(@t2, current_user)
    @total = Order.total_monthly(@t2, current_user)
    if current_user.partner?
      @total = @total * 0.30
    end
    # days_number = Time.days_in_month(Date.today.month, Date.today.year)
    # @days = Array.new(days_number, 0 )
    # @sites.each do |site|
    #   visitors = site.visitors.last_month
    #   visitors.each do |visitor|
    #     @days[visitor.created_at.mday-1] += 1
    #   end
    # end
  end

  # def show_day
  #   @hours = Array.new(24, 0 )
  #   @sites = current_user.sites.includes(:product, :orders, :visitors)
  #   @sites.each do |site|
  #     visitors = site.visitors.last_day
  #     visitors.each do |visitor|
  #       @hours[visitor.created_at.localtime.hour] += 1
  #     end
  #   end
  #
  #   # respond_to do |format|
  #   #   format.js
  #   # end
  # end


  def show_custom_month
    Groupdate.time_zone = "Europe/Warsaw"
    @flag = false
    hour_flag = params[:hour_flag] == "on" ? true : false
    if params[:startdate].blank?
      @t1 = Time.now - 30.day
    else
      @t1 = Time.parse(params[:startdate])
    end
    if params[:enddate].blank?
      @t2 = Time.now
    else
      @t2 = Time.parse(params[:enddate])
    end
    diff = ((@t2 - @t1) / 1.hour).round
    if diff <= 48 || hour_flag
      @flag = true
    end
    if params[:site_url].blank?
      @sites = current_user.sites.includes(:product, :orders, :visitors).where(visitors: {created_at: @t1..@t2, uniq: true}).order(visitors_count: :desc).paginate(:page => params[:page])
    else
      @sites = current_user.sites.includes(:product, :orders, :visitors).where(visitors: {created_at: @t1..@t2, uniq: true}, id: params[:site_url]).paginate(:page => params[:page])
    end



  end
end
#Visitor.all.where(created_at: (Date.current - (Date.today - date).to_i.day)..Date.current)
#(Date.today - date).to_i

app/helpers/dashboard_helper.rb
module DashboardHelper
  def wrap_text(txt, col = 80)
  txt.gsub(/(.{1,#{col}})(?: +|$\n?)|(.{1,#{col}})/,
    "\\1\\2\n")
  end
end

app/views/views/dashboard/index.html.haml
.row
  .col-md-8.col-lg-8.col-sm-8
    .row
      .col-md-8.col-lg-8.col-sm-4.wrap#menu
        %h1 Ostatnie Zamówienia
        - @orders.take(4).each do |order|
          %p
            = order.site.url
            %span
              = order.name
              = order.total
              = order.status
          %hr
      .col-md-4.col-lg-4.col-sm-8#news
        %h1 Linki
        = link_to "Twoje linki na strony", products_path, class: 'btn btn-info'

    .row
      .col-md-4.col-lg-4.col-sm-4#subtotal
        %h1 Ten miesiąc
        %h1= "#{@total} PLN"
        = link_to "Podsumowanie", summary_path, class: "btn btn-md btn-primary"

      .col-md-8.col-lg-8.col-sm-8#chart
        %h1 Ostatnie 7 dni
        = line_chart Visitor.group_by_day(:created_at, range: @t1..@t2).where(uniq:true).count, height: "250px", width: "550px", library: {backgroundColor: "#FE9800"}


  .col-md-3.col-lg-3.col-sm-3.wrap#sites
    %h1 Top 10 miesiąca
    - @sites.each do |site|
      %p
        = site.url
        %span{style: "color: black"}
          %span.badge.badge-visitors= site.visitors.length
      %hr
    = link_to "Przejdź do stron", sites_path, class: "btn btn-primary"
%script
  $('option').each(function(){
  var text=$(this).text()
  if (text.length > 59) {
  $(this).val(text).text(text.slice(0,95)+'…'+ text.slice(-5));
  }
  })

app/views/views/dashboard/show_custom_month.html.haml
= javascript_include_tag "//www.google.com/jsapi", "chartkick"
.sites-page
  .row
    %div.panel.panel-default.col-md-10.col-md-offset-1#canvasdrawboard
      -#%canvas#canvas
      - if @flag == true
        = line_chart Visitor.group_by_hour(:created_at, range: @t1..@t2).where(uniq:true).count
      - else
        = line_chart Visitor.group_by_day(:created_at, range: @t1..@t2).where(uniq:true).count

      = form_tag({:controller => "dashboard", :action => "show_custom_month"}, class:"chart-form") do
        %input#startdate{type: "text", name: "startdate", placeholder: "start"}
        %input#enddate{type: "text", name: "enddate", placeholder: "koniec"}
        %input{type: "checkbox", name: "hour_flag"}  show hours?
        %br
          = select_tag "site_url", options_from_collection_for_select(current_user.sites.order(visitors_count: :desc), "id", "url")
        %br
        = submit_tag 'filtruj', class: 'btn btn-sm btn-primary'

  .row

  %table.table.table-hover.wrap.tablesorter
    %thead
      %tr
        %th{width: "5%"} #ID
        %th{width: "40%"} #URL
        %th Unikalne
        %th Odsłony
        %th Zamówienia
        %th  Ratio
        %th Produkt
    %tbody
      - @sites.each do |site|
        %tr
          %td= site.id
          %td= site.url
          %td= site.visitors.length
          %td= site.visitors_count
          %td= site.orders.where(created_at: @t1..@t2).length
          - if site.visitors.length != 0 && site.orders.length != 0
            %td= "1/#{site.visitors.length / site.orders.length}"
          - else
            %td
              0/#{site.visitors.length}
          %td= site.product.name

  %script
    $('#startdate').datepicker({dateFormat: 'yy-mm-dd'});
    $('#enddate').datepicker({dateFormat: 'yy-mm-dd'});
    $('option').each(function(){
    var text=$(this).text()
    if (text.length > 59) {
    $(this).val(text).text(text.slice(0,95)+'…'+ text.slice(-5));
    }
    })
    $(".table").tablesorter();

app/views/views/dashboard/show_day.js.erb
var hours_values = new Array();


<% @hours.each do |hour| %>
hours_values.push(<%= hour %>);
<%end%>
var label = new Array();
for (i=0; i < <%= @hours.count %>; i++) {
    label.push(i.toString());
}
var lineChartData = {
    labels : label,
    datasets : [
        {
            label: "My First dataset",
            fillColor : "rgba(220,220,220,0.2)",
            strokeColor : "rgba(220,220,220,1)",
            pointColor : "rgba(220,220,220,1)",
            pointStrokeColor : "#fff",
            pointHighlightFill : "#fff",
            pointHighlightStroke : "rgba(220,220,220,1)",
            data : hours_values
        }

    ]
};
$( "#canvas" ).remove();
$('#canvasdrawboard').append('<canvas height="400" id="canvas" width="900"></canvas>');
var ctx = document.getElementById("canvas").getContext("2d");
window.myLine = new Chart(ctx).Line(lineChartData, {
    responsive: true
});

app/views/views/dashboard/show_month.html.haml
- @days.each do |day|
  %td= day

app/views/views/dashboard/show_month.js.erb
function daysInMonth(month,year) {
    return new Date(year, month, 0).getDate();
}
var data_values = new Array();
<% @days.each do |day| %>
data_values.push(<%= day %>);
<%end%>
var label = new Array();
for (i=1; i < <%= @days.count %>; i++) {
    label.push(i.toString());
}

var lineChartData = {
    labels : label,
    datasets : [
        {
            label: "My First dataset",
            fillColor : "rgba(220,220,220,0.2)",
            strokeColor : "rgba(220,220,220,1)",
            pointColor : "rgba(220,220,220,1)",
            pointStrokeColor : "#fff",
            pointHighlightFill : "#fff",
            pointHighlightStroke : "rgba(220,220,220,1)",
            data : data_values
        }

    ]
};
$( "#canvas" ).remove();
$('#canvasdrawboard').append('<canvas height="400" id="canvas" width="900"></canvas>');
var ctx = document.getElementById("canvas").getContext("2d");
window.myLine = new Chart(ctx).Line(lineChartData, {
    responsive: true
});

app/views/views/dashboard/show_week.js.erb
function daysInMonth(month,year) {
    return new Date(year, month, 0).getDate();
}
var data_values = new Array();
<% @days.each do |day| %>
data_values.push(<%= day %>);
<%end%>

var lineChartData = {
    labels : ["Poniedziałek","Wtorek","Środa","Czwartek","Piątek","Sobota","Niedziela"],
    datasets : [
        {
            label: "My First dataset",
            fillColor : "rgba(220,220,220,0.2)",
            strokeColor : "rgba(220,220,220,1)",
            pointColor : "rgba(220,220,220,1)",
            pointStrokeColor : "#fff",
            pointHighlightFill : "#fff",
            pointHighlightStroke : "rgba(220,220,220,1)",
            data : data_values
        }

    ]
};
$( "#canvas" ).remove();
$('#canvasdrawboard').append('<canvas height="400" id="canvas" width="900"></canvas>');
var ctx = document.getElementById("canvas").getContext("2d");
window.myLine = new Chart(ctx).Line(lineChartData, {
    responsive: true
});